# Generated by Django 3.1.7 on 2021-02-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('date', models.CharField(max_length=255, verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=255, verbose_name='Место жительства')),
                ('education', models.TextField(verbose_name='Образование')),
                ('job', models.CharField(max_length=255, verbose_name='Специальность')),
                ('department', models.CharField(max_length=255, verbose_name='Подразделение')),
                ('salary', models.CharField(max_length=255, verbose_name='Оклад')),
                ('employment_date', models.CharField(max_length=255, verbose_name='Дата прихода в фирму')),
                ('last_promotion_date', models.CharField(max_length=255, verbose_name='Дата последнего назначения')),
            ],
        ),
    ]
