# Generated by Django 3.1.7 on 2021-02-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateTimeField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_date',
            field=models.DateTimeField(max_length=255, verbose_name='Дата прихода в фирму'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_promotion_date',
            field=models.DateTimeField(max_length=255, verbose_name='Дата последнего назначения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Оклад ($)'),
        ),
    ]
