#!/usr/bin/env python3

print("Content-type: text/html")
print()
print("<!DOCTYPE html>")
print("<html lang='en'>")
print("<head>")
print("<meta charset='UTF-8'>")
print("<title>Анкета</title>")
print("</head>")
print("<body>")
print("<form action='1_handler.py' method='post' enctype='multipart/form-data'>")
print("<h1>Заполните анкету:</h1>")
print("<p>Введите ваше ФИО:")
print("<input type='text' name='NAME'>")
print("</p>")
print("<p>Введите пароль:")
print("<input type='password' name='PASS'>")
print("</p>")
print("<p>Ваш род занятий:")
print("<select name='OCCUPATION'>")
print("<option value='Инф. Технологии' selected> Инф. технологии</option>")
print("<option value='Строительство'> Строительство</option>")
print("<option value='Бизнес'> Бизнес</option>")
print("</select>")
print("</p>")
print("<p>Пол:")
print("<input type='radio' name='GENDER' value='Мужской' checked>Мужской</input>")
print("<input type='radio' name='GENDER' value='Женский'>Женский</input>")
print("</p>")
print("<p>Сведения об образовании:</p>")
print("<textarea name='EDUCATION_INFO' placeholder='Ваши сведения здесь' cols=45 rows=3></textarea>")
print("<p></p>")
print("<a>Ваши предпочтения:</a> <input name='WORK' value='Всё равно' style='margin-left:100px;' type='checkbox' checked>Всё равно</input>  <br>")
print("<a>(один или несколько вариантов)</a> <input name='WORK' value='Работа с клиентами' style='margin-left:23px;' type='checkbox'>Работа с клиентами</input> <br>")
print("<input name='WORK' value='Работа с документами' style='margin-left:245px;' type='checkbox'>Работа с документами</input> <br>")
print("<input name='WORK' value = 'Работа в одиночку' style='margin-left:245px;' type='checkbox'>Работа в одиночку</input> <br> <br>")
print("<button style='margin-left:200px;' type='reset'>Очистить</button>")
print("<button type='submit'>Подтвердить</button> <br> <br>")
print("</form> <br> <br>")
print("<form target='_blank' action='2_upload.py'>")
print("<button type='submit'>Загрузить изображение</button>")
print("</form>")
print("</body>")
print("</html>")